### ISSUE TITLE
Brak reakcji komend

### ISSUE THREAD

**Issue by szogi1910** [plx211/bfmod#27]
Wpisane komendy bfmenu, bftop, bfshop nie reagują na polecenia na say, jedynie otworzenie tych komend jest możliwe za pomocą konsoli wpisując sm_bfmenu itp

**Comment by plx211** [comment]
wpisujesz w czacie !bfmod czy bfmod?

**Comment by szogi1910** [comment]
obydwie metody i żadna nie daje efektów

**Comment by szogi1910** [comment]
Rozwiązane miałem konflikt pluginów, acz kolwiek polecam dodanie reguly aby po wpisaniu na say wylapywalo od razu po wpisaniu bfmod

**Comment by plx211** [comment]
Nie mam teraz zbytnio czasu rozwiac tego moda (studia) :(
Tak czy siak dobrze że sobie poradziłeś ;)

English:
Problem: 
Wrote cmd bftop, bfmenu, ... in 'say' don't work 
but write sm_btop, ... in console work.

Reason: 
Plugin conflict
